### ISSUE TITLE
Confirm button does not work within the accounts dialog

### ISSUE THREAD

**Issue by fabianbormann** [boost-pool/boost-wallet#2]
Steps for reproduction:

- Goto https://demo-wallet.boostpool.io/?lang=en
- Open accounts dialog
- Click "new" to generate a new seed
- Use "HelloWorld1234!" as password
- Click "confirm"

expected behavior: A new account will be created and the dialog will close
current behavior: No action

**Comment by jimcase** [comment]
https://user-images.githubusercontent.com/9588549/202144404-d25e5dd7-6b38-46f2-a2dd-55bbafb6fc36.mov

I replicated the issue.. looks good
